FROM eclipse-temurin:latest

#COPY ./gradle.tar.gz /

#RUN tar -xzvf /gradle.tar.gz && rm /gradle.tar.gz && cd /usr/bin && ln -s /gradle/latest/bin/gradle

WORKDIR /var/www/java

COPY ./interface /var/www/java/

RUN /var/www/java/gradlew build

EXPOSE 5555

CMD java -jar ./build/libs/interface-0.0.1-SNAPSHOT.jar

